# Generated by Django 4.2.2 on 2023-06-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_cardioexercise_user_exercise_user_alter_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcomment',
            name='workout_type',
        ),
    ]
