# Generated by Django 4.2.2 on 2023-07-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_remove_workoutcomment_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioexercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_type', to='fitness_app.workout'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardio_exercises_type', to='fitness_app.workout'),
        ),
    ]
