# Generated by Django 4.2.2 on 2023-07-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_cardioexercise_workout_exercise_workout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calorieintake',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cardioexercise',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set(),
        ),
    ]
