# Generated by Django 4.2.2 on 2023-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_alter_calorieintake_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardioexercise',
            name='cardio_exercise_type',
        ),
        migrations.RemoveField(
            model_name='cardioexercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cardioexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='cardio_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='total_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CalorieIntake',
        ),
        migrations.DeleteModel(
            name='CardioExercise',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
